<h4>Affine 계층</h4>

In [2]:
import numpy as np

In [3]:
X= np.random.rand(2) #입력
W= np.random.rand(2,3) #가중치
B= np.random.rand(3) #편향

In [4]:
X.shape

(2,)

In [5]:
W.shape

(2, 3)

In [6]:
B.shape

(3,)

In [7]:
Y=np.dot(X,W)+B 

In [8]:
Y.shape

(3,)

X,W,B는 각각 형상이 (2, ),(2, 3),(3, ) 인 다차원 배열입니다.
뉴런의 가중치 합은 Y=np.dot(X,W)+B처럼 계산
Y를 활성화 함수로 변환해 다음 층으로 전파하는 것이 신경망 순전파의 흐름이다.

행렬의 곱에서는 대응하는 차원의 원소 수를 일치시킵니다.

신경망의 순잔파 때 수행하는 행렬의 곱은 기하학에서는 어파인 변환 이라고 합니다.
어파인 변환을 수행하는 처리를 <b><mark>Affine 계층 </mark></b>이라는 이름으로 구협합니다.

<h4>배치용 Affine 계층</h4>

In [9]:
X_dot_W = np.array([[0,0,0],[10,10,10]])
B= np.array([1,2,3])

In [10]:
X_dot_W

array([[ 0,  0,  0],
       [10, 10, 10]])

In [11]:
X_dot_W+B

array([[ 1,  2,  3],
       [11, 12, 13]])

In [12]:
dY= np.array([[1,2,3],[4,5,6]])

In [13]:
dY

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
dB = np.sum(dY,axis=0)

In [15]:
dB

array([5, 7, 9])

<h4>배치용 Affine 계층에서 편향의 순전파 역전파</h4>

In [16]:
class Affine:
    def __init__(self,W,b):
        self.W = W
        self.b = b
        self.x= None
        self.dW = None
        self.db = None

    #순전파
    def forward(self,x):
        self.x = x
        out= np.dot(x,self.W)+self.b

        return out
        
    #역전파
    def backward(self,dout):
        dx= np.dot(dout, self.W.T)
        self.dW = np.dot(self.x.T,dout)
        self.db = np.sum(dout, axis=0)

        return dx

<h4>Softmax-with-Loss 계층</h4>

In [17]:
class SoftmaxWithLoss:
    def __init__(self):
        self.loss =None # 손실
        self.y = None #softmax의 출력
        self.t = None #정답 레이블(원-핫 벡터)

    def forward(self,x,t):
        self.t =t
        self.y=softmax(x)
        self.loss = cross_entropy_error(self.y, self.t)
        return self.loss

    def backward(self, dout=1):
        batch_size = self.t.shape[0]
        dx = (self.y - self.t) / batch_size

        return dx