In [1]:
import numpy as np

#활성화 함수
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [2]:
# 1층의 활성화 함수에서의 처리

X= np.array([1.0, 0.5])
W1= np.array([[0.1, 0.3, 0.5],[0.2, 0.4, 0.6]])
B1= np.array([0.1, 0.2, 0.3])

In [3]:
print(W1.shape)
print(X.shape)
print(B1.shape)

(2, 3)
(2,)
(3,)


In [4]:
A1 = np.dot(X,W1) + B1
print(A1)

[0.3 0.7 1.1]


In [5]:
Z1 = sigmoid(A1) #활성화 처리 (sigmoid 값을 거칠수있게)

print(A1)
print(Z1)

[0.3 0.7 1.1]
[0.57444252 0.66818777 0.75026011]


In [6]:
# 1층에서 2층으로 신호 전달

W2 = np.array([[0.1, 0.4],[0.2,0.5],[0.3,0.6]])
B2 = np.array([0.1,0.2])

In [7]:
print(Z1.shape)
print(W2.shape)
print(B2.shape)

(3,)
(3, 2)
(2,)


In [8]:
A2 = np.dot(Z1, W2) + B2
Z2 =sigmoid(A2)

In [9]:
def identity_function(x):
    return x

In [10]:
W3 = np.array([[0.1,0.3],[0.2,0.5]])
B3 = np.array([0.1,0.2])

A3 = np.dot(Z2, W3) + B3
Y = identity_function(A3)

In [11]:
print(Y)

[0.31682708 0.77338016]
