In [1]:
import numpy as np

In [2]:
a = np.array([1010, 1000, 990])
np.exp(a) / np.sum(np.exp(a)) # 소프트맥스 함수 계산

C:\Users\komi1\AppData\Local\Temp\ipykernel_17836\294143521.py:2: RuntimeWarning: overflow encountered in exp
  np.exp(a) / np.sum(np.exp(a)) # 소프트맥스 함수 계산
C:\Users\komi1\AppData\Local\Temp\ipykernel_17836\294143521.py:2: RuntimeWarning: invalid value encountered in divide
  np.exp(a) / np.sum(np.exp(a)) # 소프트맥스 함수 계산


array([nan, nan, nan])

In [3]:
c = np.max(a)
a-c

array([  0, -10, -20])

In [4]:
np.exp(a-c) / np.sum(np.exp(a-c))

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])