In [8]:
import numpy as np

In [9]:
x= np.array([[1,2],[3,4]])

In [10]:
x

array([[1, 2],
       [3, 4]])

In [11]:
y= np.array([[5,6],[7,8]])

In [12]:
y

array([[5, 6],
       [7, 8]])

In [14]:
x+y

array([[ 6,  8],
       [10, 12]])

In [15]:
2*x

array([[2, 4],
       [6, 8]])